Could not retrieve data from Experimentation service: Error: getaddrinfo EAI_AGAIN default.exp-tas.com
Language server is set to Microsoft.
Acquiring model 'intellisense-members-lstm' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Couldn't reach service Error Message: getaddrinfo EAI_AGAIN prod.intellicode.vsengsaas.visualstudio.com, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: getaddrinfo EAI_AGAIN prod.intellicode.vsengsaas.visualstudio.com, (Error)
No deep learning model available for Python, fall back to the default model.
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Couldn't reach service Error Message: getaddrinfo EAI_AGAIN prod.intellicode.vsengsaas.visualstudio.com, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: getaddrinfo EAI_AGAIN prod.intellicode.vsengsaas.visualstudio.com, (Error)
No model available for Python, cannot continue.
